[package]
name = "mopro-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "witness"
path = "src/bin/witness.rs"

[features]
default = ["wasmer/dylib", "calc-native-witness"]
dylib = [] # NOTE: can probably remove this if we use env config instead
gpu-benchmarks = [
    "ark-bls12-377",
    "ark-bls12-381",
    "ark-ed-on-bls12-377",
    "ark-ed-on-bls12-381",
    "ark-poly",
    "ark-poly-commit",
    "ark-sponge",
    "duration-string",
    "rand",
    "rand_chacha",
    "lazy_static",
    "ark-ec-3",
    "ark-ff-3",
    "ark-serialize-3",
    "ark-std-3",
    "ark-bls12-377-3",
]
calc-native-witness = [
    "witness",
] # experimental feature to calculate witness with witness graph
build-native-witness = [
    "witness/build-witness",
] # only enable build-native-witness feature when building the witness graph

[dependencies]
ark-circom = { git = "https://github.com/vivianjeng/circom-compat-wasm3.git" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ark-serialize = { version = "=0.4.1", features = ["derive"] }
num-bigint = { version = "=0.4.3", default-features = false, features = [
    "rand",
] }
instant = "0.1"
wasmer = { git = "https://github.com/oskarth/wasmer.git", rev = "09c7070" }
once_cell = "1.8"
ruint = { version = "1.10.0", features = ["rand", "serde", "ark-ff-04"] }

# ZKP generation
ark-ec = { version = "=0.4.1", default-features = false, features = [
    "parallel",
] }
ark-crypto-primitives = { version = "=0.4.0" }
ark-std = { version = "=0.4.0", default-features = false, features = [
    "parallel",
] }
ark-bn254 = { version = "=0.4.0" }
ark-groth16 = { version = "=0.4.0", default-features = false, features = [
    "parallel",
] }
ark-relations = { version = "0.4", default-features = false }
ark-zkey = { path = "../ark-zkey" }
witness = { path = "../../circom-witness-rs", optional = true }

# Error handling
thiserror = "=1.0.39"
color-eyre = "=0.6.2"
criterion = "=0.3.6"

# GPU explorations
ark-bls12-377 = { version = "0.4", optional = true }
ark-bls12-381 = { version = "0.3", optional = true }
ark-ed-on-bls12-377 = { version = "0.3", optional = true }
ark-ed-on-bls12-381 = { version = "0.3", optional = true }
ark-poly = { version = "0.3", optional = true }
ark-poly-commit = { version = "0.3", optional = true }
ark-sponge = { version = "0.3", optional = true }
duration-string = { version = "0.0.6", optional = true }
rand = { version = "0.8.0", optional = true }
rand_chacha = { version = "0.3.1", optional = true }
lazy_static = { version = "1.4.0", optional = true }
ark-ff = { version = "=0.4.1", default-features = false, features = [
    "parallel",
] }

# GPU explorations from mopro/Cargo.toml patch
ark-bls12-377-3 = { git = 'https://github.com/arkworks-rs/curves.git', package = 'ark-bls12-377', tag = 'v0.3.0', optional = true }
ark-ec-3 = { git = 'https://github.com/arkworks-rs/algebra.git', package = 'ark-ec', tag = 'v0.3.0', features = [
    "parallel",
], optional = true }
ark-ff-3 = { git = 'https://github.com/arkworks-rs/algebra.git', package = 'ark-ff', tag = 'v0.3.0', features = [
    "parallel",
], optional = true }
ark-serialize-3 = { git = 'https://github.com/arkworks-rs/algebra.git', package = 'ark-serialize', tag = 'v0.3.0', optional = true }
ark-std-3 = { git = 'https://github.com/arkworks-rs/std.git', package = 'ark-std', tag = 'v0.3.0', optional = true }

[build-dependencies]
color-eyre = "0.6"
enumset = "1.0.8"
wasmer = { git = "https://github.com/oskarth/wasmer.git", rev = "09c7070" }
toml = "0.8"
serde = "1.0"
serde_derive = "1.0"
# witness = { git = "https://github.com/philsippl/circom-witness-rs.git", optional = true }
